### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zzzl-h** [ZhaoJ9014/Multi-Human-Parsing_MHP#11]
Hi, 
I don't know what's wrong,
I use python2.7 and tensorflow1.2 and VOC2012 dataset
2018-11-18 21:48:15.769563: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-18 21:48:15.769595: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-18 21:48:15.769600: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-11-18 21:48:15.769604: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-18 21:48:15.769608: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-11-18 21:48:16.205096: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-18 21:48:16.205568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.8475
pciBusID 0000:01:00.0
Total memory: 7.93GiB
Free memory: 7.12GiB
2018-11-18 21:48:16.205601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2018-11-18 21:48:16.205615: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2018-11-18 21:48:16.205632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
('loading from model:', u'./savings_bgfg/pretrain.ckpt')
Traceback (most recent call last):
  File "train_step1.py", line 146, in <module>
    loss = net.train(img_batch,lab_batch)
  File "train_step1.py", line 62, in train
    ls,_ = self.sess.run([self.loss,self.train_op],feed_dict={self.inp_holder:img_batch, self.lab_holder:lab_batch})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [3364,2] and labels shape [423200]
         [[Node: bg_fg/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"](bg_fg/SparseSoftmaxCrossEntropyWithLogits/Reshape, bg_fg/SparseSoftmaxCrossEntropyWithLogits/Reshape_1)]]
         [[Node: bg_fg/Mean/_263 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_8656_bg_fg/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'bg_fg/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits', defined at:
  File "train_step1.py", line 140, in <module>
    net = network()
  File "train_step1.py", line 26, in __init__
    self.build_loss(seg_layer,lab_holder)
  File "train_step1.py", line 47, in build_loss
    seg_loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=lab_reform,logits=seg_layer))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1703, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 2486, in _sparse_softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): logits and labels must have the same first dimension, got logits shape [3364,2] and labels shape [423200]
         [[Node: bg_fg/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"](bg_fg/SparseSoftmaxCrossEntropyWithLogits/Reshape, bg_fg/SparseSoftmaxCrossEntropyWithLogits/Reshape_1)]]
         [[Node: bg_fg/Mean/_263 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_8656_bg_fg/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by Anguliachao** [comment]
@zzzl-h seems your logits output shape does not match with label shape. check ur feeding data part maybe?

**Comment by zzzl-h** [comment]
> @zzzl-h seems your logits output shape does not match with label shape. check ur feeding data part maybe?

I have checked the feeding data.
logits is (1,460,460,3), label is (1,460,460)
I don't change anything in source code and use the VOC2012 dataset.

**Comment by zzzl-h** [comment]
Can you tell me what your tensorflow version is? 
And python2 or python3?

**Comment by Anguliachao** [comment]
> Can you tell me what your tensorflow version is?
> And python2 or python3?

python 3 refer to the code , i'm not sure the tf version, generally tf1.4/tf1.5 may do the trick.

- >`seg_loss= tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=lab_reform,logits=seg_layer))
InvalidArgumentError (see above for traceback): logits and labels must have the same first dimension, got logits shape [3364,2] and labels shape [423200]
`

ur errors seems not related to version, but the feeding part. this two numbers doesn't match at all.

**Comment by zzzl-h** [comment]
> > Can you tell me what your tensorflow version is?
> > And python2 or python3?
> 
> python 3 refer to the code , i'm not sure the tf version, generally tf1.4/tf1.5 may do the trick.
> 
> * > `seg_loss= tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=lab_reform,logits=seg_layer)) InvalidArgumentError (see above for traceback): logits and labels must have the same first dimension, got logits shape [3364,2] and labels shape [423200] `
> 
> ur errors seems not related to version, but the feeding part. this two numbers doesn't match at all.

Can you run the code on your computer?
I think there are some mistakes.
In train_e2e.py, line 350:reader=data_provider('train.list'), it may be reader=data_reader('train.list')?
In train_e2e.py, line 352: One parameter is missing.
In train_e2e.py, line 35 will change the data type into float32 so it can't be feed into labels which only accepts data type int32 or int64.

**Comment by skyuuka** [comment]
I think the issue is here: https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP/issues/14#issuecomment-447530912
