### ISSUE TITLE
TypeError: Value passed to parameter 'labels' has DataType float32 not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by skyuuka** [ZhaoJ9014/Multi-Human-Parsing_MHP#14]
Run `python train_step1.py` gets the following error: 

```
Conv_bias: False
BN training: False
Conv_bias: False
BN training: False
Conv_bias: False
BN training: False
Conv_bias: False
BN training: False
Conv_bias: False
BN training: False
Conv_bias: False
Conv_bias: False
BN training: False
Conv_bias: False
BN training: False
Conv_bias: False
BN training: False
Conv_bias: False
Conv_bias: False
BN training: False
Conv_bias: True
Conv_bias: True
Traceback (most recent call last):
  File "train_step1.py", line 137, in <module>
    net = network()
  File "train_step1.py", line 25, in __init__
    self.build_loss(seg_layer,lab_holder)
  File "train_step1.py", line 45, in build_loss
    seg_loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits=seg_layer,labels=lab_reform))
  File "/home/skyuuka/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2084, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/home/skyuuka/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 7515, in sparse_softmax_cross_entropy_with_logits
    labels=labels, name=name)
  File "/home/skyuuka/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/home/skyuuka/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'labels' has DataType float32 not in list of allowed values: int32, int64
```

**Comment by skyuuka** [comment]
I figured it out finally.  
Update these [lines](https://github.com/ZhaoJ9014/Multi-Human-Parsing_MHP/blob/master/Nested_Adversarial_Networks/train_step1.py#L42-L45) to 

``` 
lab_reform = tf.expand_dims(lab_holder, -1) # 460 x 460 x 1
seg_layer = tf.image.resize_images(seg_layer, tf.shape(lab_reform)[1:3]) # 460 x 460 x 2
lab_reform = tf.squeeze(lab_reform, axis=3) # 460 x 460 x 2
seg_loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits=seg_layer,labels=lab_reform))
```
