### ISSUE TITLE
[question] Compatibility with Python 2.7 or 3.6?

### ISSUE THREAD

**Issue by archenroot** [ZhaoJ9014/Multi-Human-Parsing_MHP#18]
What is the version is supported?

I faced a issue in train_step1.py where my input image jpeg file were actually 2 paths in single string: which was failing on:
```
Reading data...
Data file= train.list
f= <_io.TextIOWrapper name='train.list' mode='r' encoding='UTF-8'>
i= VOC2012/JPEGImages/2007_000032.jpg	VOC2012/SegmentationClass/2007_000032.png

i= VOC2012/JPEGImages/2007_000032.jpg	VOC2012/SegmentationClass/2007_000032.png
rest= VOC2012/JPEGImages/2007_000032.jpg
jpgfile= VOC2012/JPEGImages/2007_000032.jpg	VOC2012/JPEGImages/2007_000032.jpg
Image path:  VOC2012/JPEGImages/2007_000032.jpg	VOC2012/JPEGImages/2007_000032.jpg
Traceback (most recent call last):
  File "train_step1.py", line 142, in <module>
    reader = data_provider('train.list')
  File "train_step1.py", line 98, in __init__
    jpg = img_reader.read_img(jpgfile,500,padding=True)
  File "/home/pegasus/proj/human-parts-parsing/Multi-Human-Parsing_MHP/Nested_Adversarial_Networks/img_reader.py", line 26, in read_img
    raw_im = np.array(Image.open(im_path).convert('RGB'), np.uint8)
  File "/home/pegasus/anaconda3/envs/mhp_nan/lib/python3.6/site-packages/PIL/Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'VOC2012/JPEGImages/2007_000032.jpg\tVOC2012/JPEGImages/2007_000032.jpg'
```

Now I removed the part "\tVOC2012/JPEGImages/2007_000032.jpg" which results into:
```
Reading data...
Data file= train.list
f= <_io.TextIOWrapper name='train.list' mode='r' encoding='UTF-8'>
i= VOC2012/JPEGImages/2007_000032.jpg	VOC2012/SegmentationClass/2007_000032.png

i= VOC2012/JPEGImages/2007_000032.jpg	VOC2012/SegmentationClass/2007_000032.png
rest= VOC2012/JPEGImages/2007_000032.jpg
jpgfile= VOC2012/JPEGImages/2007_000032.jpg
Image path:  VOC2012/JPEGImages/2007_000032.jpg
Traceback (most recent call last):
  File "train_step1.py", line 142, in <module>
    reader = data_provider('train.list')
  File "train_step1.py", line 100, in __init__
    seg = img_reader.pad(seg,np.uint8,False)
  File "/home/pegasus/proj/human-parts-parsing/Multi-Human-Parsing_MHP/Nested_Adversarial_Networks/img_reader.py", line 43, in pad
    res[start_point:start_point+a] = img
ValueError: could not broadcast input array from shape (281,500,3) into shape (281,500)
```
I use Python3, so not PIL package(only supports 2.7), but Pillow which could be causing this issue

**Comment by ddddwee1** [comment]
The code is tested on Python3.6.

We recently found some problems with the code, and we will update the code soon.
